### PR TITLE
fix(algoliaOptions): ensure we keep default options

### LINKED ISSUE #78: Default hitsPerPage not applied if algoliaOptions are specified
As soon as you specify some `algoliaOptions`, we lose the default `hitsPerPage` value. Would be better to keep that value as a default.

### PR DESCRIPTION
**Pull request by redox**
While overriding the algoliaOptions, we were losing the default
hitsPerPage query parameters.

Fix #78

### CODE REVIEW

File: test/DocSearch-test.js [hunk 1]
```diff
@@ -136,7 +166,7 @@ describe('DocSearch', () => {
       let actual = new DocSearch(options);
 
       // Then
-      expect(actual.algoliaOptions).toEqual('algoliaOptions');
+      expect(actual.algoliaOptions).toEqual({hitsPerPage: 5});
```
Comment (pixelastic) [inline test/DocSearch-test.js]: The whole PR LGTM except for this part. This test seems unrelated. I would rather set an option of `{hitsPerPage: 10}` and test that.

We want to test that it accepts the options we pass, while this test assert that we keep the default value.

Comment (redox) [inline test/DocSearch-test.js]: Right, fixing now :+1:

**Comment by redox** [comment]
@pixelastic updated :+1:
